title: dsp_praat
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tabarasaka.github.io/dsp_praat

aux_links:
  Template Repository: https://github.com/tabarasaka/dsp_praat
  
markdown: kramdown
kramdown:
  math_engine: mathjax
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
